### ISSUE TITLE
mod is not working

### ISSUE THREAD

**Issue by ponkhaan** [inglettronald/DulkirMod#23]
the settings doesnt change anything at all

**Comment by inglettronald** [comment]
Can you give me some information about your use case? Minecraft version and other mods is a good place to start. 

For example, if it turns out that you're trying to run DulkirMod through feather client or something, I can tell you that this probably isn't a good idea. Same goes for versions of minecraft that are not 1.8.9.

**Comment by ponkhaan** [comment]
i used forge 1.8.9 with only DulkirMod
